[tools]
"cargo:bkt" = "latest"
"cargo:mdsh" = "latest"
rust = "latest"
uv = "latest"

[env]
BKT_TTL = "1w"
BKT_CACHE_DIR = "./cache"

[tasks.mdsh]
description = "Update the README with data from the experiments"
wait_for = ["aggregate"]
run = "mdsh"

[tasks.update-readme]
alias = "md"
description = "Run all experiments and update the README"
depends = ["experiments", "aggregate", "mdsh"]

[tasks.clear-cache]
description = "Remove all cached results"
run = ["rm -r ./cache"]
